# Generated by Django 5.0.7 on 2024-07-25 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial'), ('PERSONAL_ID', 'Personal ID'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_shared', models.BooleanField(default=False)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='File type (e.g. PDF, Word, Excel, etc.)', max_length=50)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
