# Generated by Django 5.0.7 on 2024-07-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_document_share_delete_documents'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='share',
            table='doc_share',
        ),
    ]
