# Generated by Django 5.0.7 on 2024-09-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_accessrequest_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
