# Generated by Django 5.0.7 on 2024-09-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
