# Generated by Django 5.0.7 on 2024-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_documentmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
