# Generated by Django 5.0.7 on 2024-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
