# Generated by Django 5.0.7 on 2024-09-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
